[project]
name = "aiparser"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "dynaconf>=3.2.11",
    "icecream>=2.1.5",
    "openai>=1.97.1",
    "pandas>=2.3.1",
    "pyqt5",
    "requests>=2.32.4",
]
